---
- name: Deploy Web App
  hosts: web_apps
  become: yes

  tasks:
  - name: Install Git
    yum:
      name: git
      state: present

  - name: Host code
    git:
      repo: https://github.com/Elijahleke/food_app.git
      dest: /var/www/html

...