[web_apps]
calc_app ansible_host=172.31.80.239 ansible_user=ec2-user ansible_ssh_private_key_file=/home/ec2-user/SSHcee.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'

ecomm ansible_host=172.31.81.133 ansible_user=fedora ansible_ssh_private_key_file=/home/ec2-user/SSHcee.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[mobile]
game_app ansible_host=172.31.93.164 ansible_user=ec2-user ansible_ssh_private_key_file=/home/ec2-user/SSHcee.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'
sm_app ansible_host=172.31.82.8 ansible_user=fedora ansible_ssh_private_key_file=/home/ec2-user/SSHcee.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'

