---
- name: Install and configure httpd on web apps
  hosts: web_apps
  become: yes
  tasks:
    - name: Install Apache (httpd) on Amazon Linux
      when: ansible_distribution == 'Amazon'
      yum:
        name: httpd
        state: present

    - name: Install Apache (httpd) on Fedora
      when: ansible_distribution == 'Fedora'
      shell: dnf install -y httpd
      args:
        creates: /usr/sbin/httpd

    - name: Ensure httpd service is running and enabled
      service:
        name: httpd
        state: started
        enabled: yes