---
- name: Variables Demo
  hosts: mobile
  become: yes
  vars:
    tutor: Cynthia

  tasks:
  - name: Update Dynamic page
    template:
      src: infoweb.j2
      dest: /var/www/html/infoweb.html
...