---
  - name: Update static page
    copy:
      src: onepage.html
      dest: /var/www/html/onepage.html

  - name: Update infoweb page
    template:
      src: onepage.j2
      dest: /var/www/html/infoweb.html
...